// Generated by CoffeeScript 1.9.3

/*
 * v.build config
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var _env, _root, args, cfg, path, ref;

path = require('path');

cfg = require('../config.json');

args = require('yargs').argv;

_root = process.env.INIT_CWD;

_env = (ref = args.e || args.env) != null ? ref : 'dev';

module.exports = {
  env: _env,
  spaceName: "sbLib",
  root: _root,
  distPath: './dist/',
  jsPath: './_src/',
  lessPath: './_src/_less/',
  tplPath: './_src/_tpl/',
  imgPath: './_src/img/',
  jsLibPath: './_src/vendor/',
  watchFiles: ['./_src/**/*.js', './_src/_less/**/*.less', './_src/_tpl/**/*.html', '!.DS_Store']
};
