// Generated by CoffeeScript 1.9.3

/*
 * v.build config
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var _author, _desc, _email, _root, _version, args, cfg, path, ref, ref1, ref2, ref3;

path = require('path');

cfg = require('../config.json');

args = require('yargs').argv;

_root = process.env.INIT_CWD;

_version = (ref = args.v || args.version) != null ? ref : '0.0.1';

_desc = (ref1 = args.d || args.desc) != null ? ref1 : '';

_author = (ref2 = args.author) != null ? ref2 : 'lmtdit';

_email = (ref3 = args.email) != null ? ref3 : 'lmtdit@gmail.com';

module.exports = {
  modName: path.parse(_root).name,
  version: _version,
  desc: _desc,
  author: _author,
  email: _email,
  spaceName: 'sbLib',
  root: _root,
  distPath: './dist/',
  jsPath: './_src/',
  lessPath: './_src/_less/',
  tplPath: './_src/_tpl/',
  imgPath: './_src/img/',
  jsLibPath: './_src/vendor/',
  watchFiles: ['./_src/**/*.js', './_src/_less/**/*.less', './_src/_tpl/**/*.html', '!.DS_Store']
};
