// Generated by CoffeeScript 1.9.1

/*
 * v.build config
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var _env, _envs, _isDebug, args, cfg, path, ref, ref1, st_root;

path = require('path');

cfg = require('../config.json');

args = require('yargs').argv;

st_root = process.env.INIT_CWD;

_env = (ref = args.e || args.env) != null ? ref : 'dev';

_isDebug = (ref1 = args.d || args.debug) != null ? ref1 : false;

_envs = cfg.envs;

module.exports = {
  env: _env,
  isDebug: _isDebug,
  distPath: './dist/',
  imgPath: './img/',
  jsPath: './js/',
  lessPath: './js/_less/',
  tplPath: './js/_tpl/',
  jsLibPath: './js/vendor/',
  watchFiles: ['./js/**/*.js', './js/_less/**/*.less', './js/_tpl/**/*.html', '!.DS_Store']
};
